### ISSUE TITLE
Erro ao usar a função try_from do  Cpf 

### ISSUE THREAD

**Issue by enieber** [ricardodarocha/validador-br#4]
Erro ao usar a função try_from:

![image](https://github.com/ricardodarocha/validador-br/assets/7907068/d5b18080-e3b0-49fe-a696-f9dc01cf35d3)

Codigo:

`let cpf = Cpf::try_from(str)`

**Comment by cuducos** [comment]
`str` no teu caso parece ser `String` e não `&str`. Com a segundam, aqui funcionou:

```rust
use validador_br::types::Cpf;

fn main() {
    let cpf = Cpf::try_from("12345678911");

    match cpf {
        Ok(value) => println!("{:?}", value.0),
        Err(err) => println!("{err}"),
    }
}

**Comment by ricardodarocha** [comment]
Vamos implementar o trait `FromStr` em breve
Por hora, voce pode trabalhar com String
Grato

**Comment by enieber** [comment]
funcionou @ricardodarocha , valeu pelas dicas @cuducos
